language: julia
os:
  - osx
  - linux
  - windows  
julia:
  - 1.4 
beofre_script:
  - julia -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/mathn7/Test_Optinum.git"))'

notifications:
  email: false
